apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-app
  labels:
    app: feeds-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeds-app
  template:
    metadata:
      labels:
        app: feeds-app
    spec:
      containers:
        - name: feeds-app
          ports:
            - containerPort: 8081
          image: 179266296566.dkr.ecr.us-east-1.amazonaws.com/feed:latest
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "lesson3"
            - name: POSTGRES_HOST
              value: "database-1.c5ejl9ytcwto.us-east-1.rds.amazonaws.com"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_PROFILE
              value: "default"
            - name: AWS_BUCKET
              value: "space-finder-photos-0a07cb90da45"
            - name: JWT_SECRET
              value: "testing"
            - name: AWS_ACCESS_KEY_ID
              value: "ASIASTPI2TL3LC5FKZNO"
            - name: AWS_SECRET_ACCESS_KEY
              value: "fmOwFYNubWnaJN4J859J+R31mg4iyso+42A6IUaq"
            - name: AWS_SESSION_TOKEN
              value: "FwoGZXIvYXdzEPr//////////wEaDMGR8wJzCJQ4GtcwtiLVAdzH6EaLA1P/gDOGeBt/xq5GQXVR9rok4byAChj5Rk8waIAEwd3ZwGtKctB1PNl5EH3BJfH8F0xmwsGPKHyh2ws2bYg/eWHpNrl8v/i0hXyOuxV1uIplb/FQkepznZeUmsYZ4x5DWJ8y6eHP0N8201Wbjq+aIET8kMPeNa3EtnEFz7EOJIpVjX2iOC88U0zoJueK/UbWPfQdyyxzfQPQ9RzHubTV0JLUTJCN9WWOd42XgFWnnI7PILWr2CZSQ2gPSbcyKZAXmP2BrNp6ZeO1ZwIWSf0u7ij6uvKnBjIt4nDt6Ctq7GcAE3VlbL5OwN2kb5GHPCKM+uEa396VfgtS3IupFderHpRsCvE+"
---
apiVersion: v1
kind: Service
metadata:
  name: feeds-app
  labels:
    run: feeds-app
spec:
  ports:
    - name: feeds-app
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: feeds-app
